 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/answer_forms", type: :request do
  
  # AnswerForm. As you add validations to AnswerForm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AnswerForm.create! valid_attributes
      get answer_forms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      answer_form = AnswerForm.create! valid_attributes
      get answer_form_url(answer_form)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_answer_form_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      answer_form = AnswerForm.create! valid_attributes
      get edit_answer_form_url(answer_form)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AnswerForm" do
        expect {
          post answer_forms_url, params: { answer_form: valid_attributes }
        }.to change(AnswerForm, :count).by(1)
      end

      it "redirects to the created answer_form" do
        post answer_forms_url, params: { answer_form: valid_attributes }
        expect(response).to redirect_to(answer_form_url(AnswerForm.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AnswerForm" do
        expect {
          post answer_forms_url, params: { answer_form: invalid_attributes }
        }.to change(AnswerForm, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post answer_forms_url, params: { answer_form: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested answer_form" do
        answer_form = AnswerForm.create! valid_attributes
        patch answer_form_url(answer_form), params: { answer_form: new_attributes }
        answer_form.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the answer_form" do
        answer_form = AnswerForm.create! valid_attributes
        patch answer_form_url(answer_form), params: { answer_form: new_attributes }
        answer_form.reload
        expect(response).to redirect_to(answer_form_url(answer_form))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        answer_form = AnswerForm.create! valid_attributes
        patch answer_form_url(answer_form), params: { answer_form: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested answer_form" do
      answer_form = AnswerForm.create! valid_attributes
      expect {
        delete answer_form_url(answer_form)
      }.to change(AnswerForm, :count).by(-1)
    end

    it "redirects to the answer_forms list" do
      answer_form = AnswerForm.create! valid_attributes
      delete answer_form_url(answer_form)
      expect(response).to redirect_to(answer_forms_url)
    end
  end
end
