 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/client_forms", type: :request do
  
  # ClientForm. As you add validations to ClientForm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ClientForm.create! valid_attributes
      get client_forms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      client_form = ClientForm.create! valid_attributes
      get client_form_url(client_form)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_client_form_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      client_form = ClientForm.create! valid_attributes
      get edit_client_form_url(client_form)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ClientForm" do
        expect {
          post client_forms_url, params: { client_form: valid_attributes }
        }.to change(ClientForm, :count).by(1)
      end

      it "redirects to the created client_form" do
        post client_forms_url, params: { client_form: valid_attributes }
        expect(response).to redirect_to(client_form_url(ClientForm.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ClientForm" do
        expect {
          post client_forms_url, params: { client_form: invalid_attributes }
        }.to change(ClientForm, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post client_forms_url, params: { client_form: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested client_form" do
        client_form = ClientForm.create! valid_attributes
        patch client_form_url(client_form), params: { client_form: new_attributes }
        client_form.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the client_form" do
        client_form = ClientForm.create! valid_attributes
        patch client_form_url(client_form), params: { client_form: new_attributes }
        client_form.reload
        expect(response).to redirect_to(client_form_url(client_form))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        client_form = ClientForm.create! valid_attributes
        patch client_form_url(client_form), params: { client_form: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested client_form" do
      client_form = ClientForm.create! valid_attributes
      expect {
        delete client_form_url(client_form)
      }.to change(ClientForm, :count).by(-1)
    end

    it "redirects to the client_forms list" do
      client_form = ClientForm.create! valid_attributes
      delete client_form_url(client_form)
      expect(response).to redirect_to(client_forms_url)
    end
  end
end
