version: "3" 
services:
  web_formaio:
    image: alexrogna/formaio_web:prod
    expose:
      - 3000
    env_file:
      - .env/production/database_formaio
      - .env/production/web_formaio
    environment:
      - VIRTUAL_HOST=formaio.alexrogna.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=formaio.alexrogna.com
    networks:
      - proxy
    restart: always

  database_formaio:
    image: postgres
    env_file:
      - .env/production/database_formaio
    volumes:
      - db_data_formaio:/var/lib/postgresql/data
    networks:
      - proxy
    restart: always
    
  db-migrator_formaio:
    image: alexrogna/formaio_web:prod
    command: ["./wait-for", "--timeout=300", "database_formaio:5432", "--", "bin/rails", "db:create" , "db:migrate"]
    env_file:
      - .env/production/database_formaio
      - .env/production/web_formaio
volumes:
  db_data_formaio:
networks:
  proxy: